
services:
  gateway:
    image: vozymanos/openmrs-reference-application-3-gateway:${OPENMRS_VERSION_TAG:-latest}
    restart: "unless-stopped"
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  frontend:
    image: vozymanos/openmrs-reference-application-3-frontend:${OPENMRS_VERSION_TAG:-latest}
    restart: "unless-stopped"
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: "/openmrs/spa/config-core_demo.json, /openmrs/spa/config-vym_EC.json"
      SPA_DEFAULT_LOCALE: es_EC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    depends_on:
      - backend
    volumes:
      - ./site-content/media:/usr/share/nginx/html/media

  backend:
    image: vozymanos/openmrs-reference-application-3-backend:${OPENMRS_VERSION_TAG:-latest}
    restart: "unless-stopped"
    depends_on:
      - db
    env_file: "env/openmrs.env"
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_DB_DRIVER_CLASS: "com.mysql.cj.jdbc.Driver"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data

  # MariaDB
  db:
    image: mariadb:10.11.7
    restart: "unless-stopped"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    env_file: "env/mysqld.env"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'mysql --user=$${MYSQL_USER:-openmrs} --password=$${MYSQL_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\"'"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: ~
  openmrs-data: ~
